 import React from 'react'
 import type { Metadata } from "next";
 import AllProducts from '@/app/- components/AllProducts/AllProducts';

 export const metadata: Metadata = {
  title: "E-AllProducts 🧦🌍",
  description: "Generated by create next app",
};
export default function Products() { 
  

  return (
 <>
 < AllProducts/>
</>
  )
}
