import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./- components/Navbar";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { Toaster } from "@/components/ui/sonner";
import MySessionProvider from "@/mySessionProvider/MySessionProvider";
import CartContextProvider from "@/Context/CartContext";
// import { WishlistProvider } from "@/Context/WishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MySessionProvider>
            <CartContextProvider>
          {/* <WishlistProvider> */}
              <Navbar />
              {children}
          {/* </WishlistProvider> */}
            </CartContextProvider>
        </MySessionProvider>

        <Toaster />
      </body>
    </html>
  );
}
